services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # maps host port 80 to nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web