const DATA_MAP = {
    'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Kadapa', 'Krishna', 'Kurnool', 'Prakasam', 'Visakhapatnam', 'Vizianagaram', 'West Godavari'],
    'Arunachal Pradesh': ['Namsai'],
    'Assam': ['Baksa', 'Barpeta', 'Bongaigaon', 'Darrang', 'Dhemaji', 'Dhubri', 'Goalpara', 'Hailakandi', 'Jorhat', 'Kamrup', 'Kamrup Metropolitan', 'Karbi Anglong', 'Lakhimpur', 'Nagaon', 'Sonitpur', 'Udalguri'],
    'Bihar': ['Aurangabad', 'Begusarai', 'Bhagalpur', 'Jamui', 'Kaimur', 'Katihar', 'Khagaria', 'Patna'],
    'Chhattisgarh': ['Balod', 'Balrampur', 'Bastar', 'Bemetara', 'Dhamtari', 'Durg', 'Gariaband', 'Jashpur', 'Kanker', 'Korba', 'Mungeli', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
    'Goa': ['North Goa', 'South Goa'],
    'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Chhota Udaipur', 'Dang', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kachchh', 'Kheda', 'Morbi', 'Narmada', 'Navsari', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'],
    'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Fatehabad', 'Hisar', 'Jhajjar', 'Jind', 'Kurukshetra', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Sirsa', 'Sonipat', 'Yamunanagar'],
    'Himachal Pradesh': ['Bilaspur', 'Hamirpur', 'Kangra', 'Kullu', 'Sirmaur', 'Una'],
    'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Gumla', 'Khunti', 'Ramgarh', 'Ranchi'],
    'Karnataka': ['Ballari', 'Bangalore Rural', 'Bangalore Urban', 'Bidar', 'Chikkamagaluru', 'Chitradurga', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Raichur', 'Shivamogga', 'Udupi', 'Uttara Kannada', 'Yadgir'],
    'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
    'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Neemuch', 'Panna', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Vidisha'],
    'Maharashtra': ['Akola', 'Amravati', 'Aurangabad', 'Beed', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Jalna', 'Kolhapur', 'Latur', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
    'Meghalaya': ['East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'West Garo Hills'],
    'Nagaland': ['Dimapur'],
    'Odisha': ['Balangir', 'Bargarh', 'Cuttack', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sundargarh'],
    'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Patiala', 'Sangrur', 'Tarn Taran'],
    'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Rajsamand', 'Sikar', 'Sirohi', 'Udaipur'],
    'Tamil Nadu': ['Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Erode', 'Kancheepuram', 'Karur', 'Krishnagiri', 'Madurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga', 'Tenkasi', 'Thanjavur', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
    'Telangana': ['Mancherial', 'Nalgonda', 'Rajanna Sircilla', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural'],
    'Uttarakhand': ['Udham Singh Nagar'],
}
