"""State -> district lists used by Farmer and other location dropdowns."""

STATE_DISTRICTS = {
    'Andhra Pradesh': [
        'Alluri Sitharama Raju',
        'Anantapur',
        'Ananthapuramu',
        'Annamayya',
        'Bapatla',
        'Chittoor',
        'East Godavari',
        'Eluru',
        'Guntur',
        'Krishna',
        'Kurnool',
        'Nandyal',
        'Nellore',
        'Palnadu',
        'Prakasam',
        'Sri Sathya Sai',
        'Srikakulam',
        'Visakhapatnam',
        'Vizianagaram',
        'West Godavari',
    ],
    'Arunachal Pradesh': [
        'Changlang',
        'East Siang',
        'Lohit',
        'Lower Dibang Valley',
        'Lower Subansiri',
        'Namsai',
        'Papum Pare',
        'Tirap',
    ],
    'Assam': [
        'Baksa',
        'Barpeta',
        'Biswanath',
        'Bongaigaon',
        'Cachar',
        'Chirang',
        'Darrang',
        'Dhemaji',
        'Dhubri',
        'Dibrugarh',
        'Goalpara',
        'Golaghat',
        'Hailakandi',
        'Hojai',
        'Jorhat',
        'Kamrup',
        'Kamrup Metropolitan',
        'Karbi Anglong',
        'Karimganj',
        'Kokrajhar',
        'Lakhimpur',
        'Nagaon',
        'Nalbari',
        'Sonitpur',
        'Tinsukia',
        'Udalguri',
    ],
    'Bihar': [
        'Araria',
        'Aurangabad',
        'Banka',
        'Begusarai',
        'Bhagalpur',
        'Bhojpur',
        'Buxar',
        'Darbhanga',
        'Gaya',
        'Gopalganj',
        'Jamui',
        'Jehanabad',
        'Kaimur',
        'Katihar',
        'Khagaria',
        'Kishanganj',
        'Lakhisarai',
        'Madhepura',
        'Madhubani',
        'Munger',
        'Muzaffarpur',
        'Nalanda',
        'Nawada',
        'Patna',
        'Purnia',
        'Rohtas',
        'Saharsa',
        'Samastipur',
        'Saran',
        'Sheikhpura',
        'Sheohar',
        'Sitamarhi',
        'Siwan',
        'Supaul',
        'Vaishali',
    ],
    'Chhattisgarh': [
        'Balod',
        'Bastar',
        'Bemetara',
        'Bilaspur',
        'Dantewada',
        'Dhamtari',
        'Durg',
        'Gariaband',
        'Janjgir-Champa',
        'Jashpur',
        'Kabirdham',
        'Kanker',
        'Kondagaon',
        'Korba',
        'Mahasamund',
        'Mungeli',
        'Raigarh',
        'Raipur',
        'Rajnandgaon',
        'Sukma',
        'Surajpur',
        'Surguja',
    ],
    'Delhi': [
        'New Delhi',
        'South East Delhi',
    ],
    'Goa': [
        'North Goa',
        'South Goa',
    ],
    'Gujarat': [
        'Ahmedabad',
        'Amreli',
        'Anand',
        'Banaskantha',
        'Bharuch',
        'Bhavnagar',
        'Chhota Udaipur',
        'Dang',
        'Devbhumi Dwarka',
        'Gandhinagar',
        'Gir Somnath',
        'Jamnagar',
        'Junagadh',
        'Kachchh',
        'Kheda',
        'Morbi',
        'Narmada',
        'Navsari',
        'Patan',
        'Porbandar',
        'Rajkot',
        'Sabarkantha',
        'Surat',
        'Surendranagar',
        'Tapi',
        'Vadodara',
        'Valsad',
    ],
    'Haryana': [
        'Ambala',
        'Bhiwani',
        'Charkhi Dadri',
        'Faridabad',
        'Fatehabad',
        'Gurugram',
        'Hisar',
        'Jhajjar',
        'Jind',
        'Kaithal',
        'Karnal',
        'Kurukshetra',
        'Mahendragarh',
        'Nuh',
        'Palwal',
        'Panchkula',
        'Panipat',
        'Rewari',
        'Rohtak',
        'Sirsa',
        'Sonipat',
        'Yamunanagar',
    ],
    'Himachal Pradesh': [
        'Bilaspur',
        'Chamba',
        'Hamirpur',
        'Kangra',
        'Kullu',
        'Mandi',
        'Sirmaur',
        'Solan',
        'Una',
    ],
    'Jharkhand': [
        'Bokaro',
        'Chatra',
        'Deoghar',
        'Dhanbad',
        'Dumka',
        'Garhwa',
        'Giridih',
        'Godda',
        'Gumla',
        'Hazaribag',
        'Jamtara',
        'Khunti',
        'Latehar',
        'Lohardaga',
        'Pakur',
        'Ramgarh',
        'Ranchi',
    ],
    'Karnataka': [
        'Ballari',
        'Bangalore Rural',
        'Bangalore Urban',
        'Bidar',
        'Bijapur',
        'Chitradurga',
        'Davanagere',
        'Dharwad',
        'Hassan',
        'Haveri',
        'Kalaburagi',
        'Kodagu',
        'Kolar',
        'Koppal',
        'Mandya',
        'Mysore',
        'Mysuru',
        'Raichur',
        'Udupi',
        'Uttara Kannada',
        'Yadgir',
    ],
    'Kerala': [
        'Alappuzha',
        'Ernakulam',
        'Idukki',
        'Kannur',
        'Kasaragod',
        'Kollam',
        'Kottayam',
        'Kozhikode',
        'Malappuram',
        'Palakkad',
        'Pathanamthitta',
        'Thiruvananthapuram',
        'Thrissur',
        'Wayanad',
    ],
    'Madhya Pradesh': [
        'Agar Malwa',
        'Alirajpur',
        'Anuppur',
        'Balaghat',
        'Barwani',
        'Betul',
        'Bhind',
        'Bhopal',
        'Burhanpur',
        'Chhatarpur',
        'Chhindwara',
        'Damoh',
        'Datia',
        'Dewas',
        'Dhar',
        'Dindori',
        'Guna',
        'Gwalior',
        'Harda',
        'Hoshangabad',
        'Indore',
        'Jabalpur',
        'Jhabua',
        'Katni',
        'Khandwa',
        'Khargone',
        'Mandla',
        'Mandsaur',
        'Morena',
        'Neemuch',
        'Panna',
        'Raisen',
        'Rajgarh',
        'Ratlam',
        'Rewa',
        'Sagar',
        'Satna',
        'Sehore',
        'Seoni',
        'Shahdol',
        'Shajapur',
        'Sheopur',
        'Shivpuri',
        'Sidhi',
        'Singrauli',
        'Tikamgarh',
        'Ujjain',
        'Umaria',
        'Vidisha',
    ],
    'Maharashtra': [
        'Akola',
        'Amravati',
        'Aurangabad',
        'Beed',
        'Bhandara',
        'Chandrapur',
        'Dhule',
        'Gadchiroli',
        'Gondia',
        'Hingoli',
        'Jalgaon',
        'Jalna',
        'Kolhapur',
        'Latur',
        'Mumbai',
        'Mumbai City',
        'Mumbai Suburban',
        'Nagpur',
        'Nanded',
        'Nandurbar',
        'Nashik',
        'Osmanabad',
        'Palghar',
        'Parbhani',
        'Pune',
        'Raigad',
        'Ratnagiri',
        'Sangli',
        'Satara',
        'Solapur',
        'Thane',
        'Wardha',
        'Washim',
        'Yavatmal',
    ],
    'Meghalaya': [
        'East Garo Hills',
        'East Jaintia Hills',
        'East Khasi Hills',
        'Eastern West Khasi Hills',
        'North Garo Hills',
        'Ri Bhoi',
        'West Garo Hills',
        'West Khasi Hills',
    ],
    'Nagaland': [
        'Dimapur',
        'Kohima',
        'Mokokchung',
        'Mon',
        'Phek',
        'Tuensang',
        'Wokha',
    ],
    'Odisha': [
        'Balangir',
        'Bargarh',
        'Bhadrak',
        'Cuttack',
        'Debagarh',
        'Dhenkanal',
        'Gajapati',
        'Ganjam',
        'Jharsuguda',
        'Kalahandi',
        'Kandhamal',
        'Kendrapara',
        'Kendujhar',
        'Khordha',
        'Koraput',
        'Malkangiri',
        'Mayurbhanj',
        'Nayagarh',
        'Nuapada',
        'Puri',
        'Rayagada',
        'Sambalpur',
        'Sundargarh',
    ],
    'Puducherry': [
        'Karaikal',
        'Puducherry',
        'Yanam',
    ],
    'Punjab': [
        'Amritsar',
        'Barnala',
        'Bathinda',
        'Faridkot',
        'Fatehgarh Sahib',
        'Fazilka',
        'Gurdaspur',
        'Hoshiarpur',
        'Jalandhar',
        'Kapurthala',
        'Ludhiana',
        'Mansa',
        'Moga',
        'Pathankot',
        'Patiala',
        'Sangrur',
        'Tarn Taran',
    ],
    'Rajasthan': [
        'Ajmer',
        'Alwar',
        'Banswara',
        'Baran',
        'Barmer',
        'Bharatpur',
        'Bhilwara',
        'Bikaner',
        'Bundi',
        'Chittorgarh',
        'Churu',
        'Dausa',
        'Dholpur',
        'Dungarpur',
        'Hanumangarh',
        'Jaipur',
        'Jaisalmer',
        'Jalore',
        'Jhalawar',
        'Jhunjhunu',
        'Jodhpur',
        'Karauli',
        'Kota',
        'Nagaur',
        'Pali',
        'Pratapgarh',
        'Rajsamand',
        'Sawai Madhopur',
        'Sikar',
        'Sirohi',
        'Tonk',
        'Udaipur',
    ],
    'Tamil Nadu': [
        'Ariyalur',
        'Chennai',
        'Coimbatore',
        'Cuddalore',
        'Dharmapuri',
        'Dindigul',
        'Erode',
        'Kanyakumari',
        'Karur',
        'Krishnagiri',
        'Madurai',
        'Nagapattinam',
        'Namakkal',
        'Nilgiris',
        'Perambalur',
        'Pudukkottai',
        'Ramanathapuram',
        'Salem',
        'Sivaganga',
        'Tenkasi',
        'Thanjavur',
        'Theni',
        'Thoothukudi',
        'Tiruchirappalli',
        'Tirunelveli',
        'Tiruppur',
        'Tiruvallur',
        'Tiruvannamalai',
        'Tiruvarur',
        'Vellore',
        'Viluppuram',
        'Virudhunagar',
    ],
    'Telangana': [
        'Adilabad',
        'Hanamkonda',
        'Hyderabad',
        'Jangaon',
        'Kamareddy',
        'Karimnagar',
        'Khammam',
        'Mahabubabad',
        'Mahbubnagar',
        'Mancherial',
        'Medak',
        'Medchal–Malkajgiri',
        'Mulugu',
        'Nagarkurnool',
        'Nalgonda',
        'Narayanpet',
        'Nirmal',
        'Nizamabad',
        'Rajanna Sircilla',
        'Ranga Reddy',
        'Siddipet',
        'Suryapet',
        'Vikarabad',
        'Wanaparthy',
    ],
    'Tripura': [
        'Dhalai',
        'Gomati',
        'North Tripura',
        'Sepahijala',
        'South Tripura',
        'Unakoti',
        'West Tripura',
    ],
    'Uttar Pradesh': [
        'Agra',
        'Aligarh',
        'Ambedkar Nagar',
        'Auraiya',
        'Ayodhya',
        'Azamgarh',
        'Bahraich',
        'Ballia',
        'Balrampur',
        'Banda',
        'Barabanki',
        'Bareilly',
        'Basti',
        'Bhadohi',
        'Bijnor',
        'Budaun',
        'Chandauli',
        'Chitrakoot',
        'Deoria',
        'Etah',
        'Etawah',
        'Firozabad',
        'Ghaziabad',
        'Gonda',
        'Gorakhpur',
        'Hamirpur',
        'Hapur',
        'Hardoi',
        'Hathras',
        'Jalaun',
        'Jaunpur',
        'Jhansi',
        'Kannauj',
        'Kanpur Dehat',
        'Kaushambi',
        'Kheri',
        'Lalitpur',
        'Lucknow',
        'Mahoba',
        'Mainpuri',
        'Mathura',
        'Mau',
        'Meerut',
        'Mirzapur',
        'Moradabad',
        'Muzaffarnagar',
        'Pilibhit',
        'Pratapgarh',
        'Rampur',
        'Saharanpur',
        'Sambhal',
        'Shamli',
        'Siddharthnagar',
        'Sitapur',
        'Sonbhadra',
        'Sultanpur',
        'Unnao',
        'Varanasi',
    ],
    'Uttarakhand': [
        'Almora',
        'Champawat',
        'Dehradun',
        'Haridwar',
        'Nainital',
        'Pauri Garhwal',
        'Udham Singh Nagar',
        'Uttarkashi',
    ],
    'West Bengal': [
        'Alipurduar',
        'Bankura',
        'Birbhum',
        'Cooch Behar',
        'Hooghly',
        'Howrah',
        'Jalpaiguri',
        'Jhargram',
        'Kolkata',
        'Murshidabad',
        'Nadia',
        'North 24 Parganas',
        'South 24 Parganas',
        'South Dinajpur',
    ],
}
