# Generated by Django 5.2.8 on 2025-12-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroundwaterLevel',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
