# Generated by Django 5.2.8 on 2025-12-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('station_name', 'district', 'state')},
        ),
    ]
