# Generated by Django 5.2.8 on 2025-12-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_station_station_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='GroundwaterLevel',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
