# Generated by Django 5.2.8 on 2025-12-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='aquifer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='aquifer_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
