# Generated by Django 5.2.8 on 2026-08-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_station_aquifer_details_station_aquifer_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
