# Generated by Django 5.2.8 on 2025-12-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0002_savedlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedLocation',
        ),
    ]
