# Generated by Django 5.2.8 on 2026-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0003_delete_savedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
