# Generated by Django 5.2.8 on 2025-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yeild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquifer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.FloatField(help_text='Original serial number from the CSV')),
                ('principal', models.CharField(help_text='Principal Aquifer System (e.g., Alluvium)', max_length=100)),
                ('code', models.CharField(help_text='Aquifer Code (e.g., AL01)', max_length=50)),
                ('name', models.CharField(help_text='Specific description or rock type', max_length=255)),
                ('age', models.CharField(help_text='Geological Age', max_length=100)),
                ('recommended', models.FloatField(help_text='Recommended value')),
                ('minimum', models.FloatField(help_text='Minimum value')),
                ('maximum', models.FloatField(help_text='Maximum value')),
            ],
            options={
                'verbose_name': 'Aquifer Data',
                'verbose_name_plural': 'Aquifer Data',
                'ordering': ['serial_number'],
            },
        ),
    ]
