# Generated by Django 5.2.8 on 2025-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yeild', '0002_aquifer'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='aquifer_area',
            field=models.FloatField(blank=True, help_text='Area from area_re field', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='aquifer_yield',
            field=models.FloatField(blank=True, help_text='Extracted numeric yield (e.g., 2.0)', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='last_api_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
